# Generated by Django 4.0.4 on 2022-08-03 09:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to='gallery/%Y/%m/%d'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='_image',
            field=models.ImageField(blank=True, null=True, upload_to='prod_images/%Y/%m/%d'),
        ),
    ]
