# Generated by Django 4.0.4 on 2022-08-16 09:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='gallery/%Y/%m/%d'), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=list, null=True, size=None),
        ),
    ]
