# Generated by Django 4.0.4 on 2022-08-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalshop', '0002_category_image_product_gallery_product_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
