# Generated by Django 4.0.4 on 2022-08-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalshop', '0004_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='_image',
        ),
    ]
